language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    sources:
    - sourceline: "deb [arch=amd64] https://kisiodigital.jfrog.io/kisiodigital/debian-local stretch main"
      key_url: "https://kisiodigital.jfrog.io/kisiodigital/api/gpg/key/public"
    packages:
    - proj=6.3.0
matrix:
  include:
  - rust: stable
    name: Linting
    before_script: rustup component add rustfmt
    script: cargo fmt --all -- --check
  - rust: stable
    name: Clippy
    before_script: rustup component add clippy
    script: cargo clippy --workspace -- -D warnings
  allow_failures:
  - rust: nightly
script:
  - cargo test --workspace --verbose
