[package]
name = "tartare-tools"
version = "0.1.0"
authors = ["David Quintanel <david.quintanel@gmail.com>", "Nicolas Bérard <nicolas.berard@kisio.org>"]
edition="2018"

[dependencies]
navitia_model = { git = "https://github.com/CanalTP/navitia_model" }
osm_transit_extractor = { git = "https://github.com/CanalTP/osm-transit-extractor" }
geo = { git = "https://github.com/georust/geo" }
structopt = "0.2.10"
env_logger = "0.6.0"
log = "0.4.6"
failure = "0.1.5"
osm-utils = { path = "./osm-utils" }
csv = "1.0.2"
zip = "0.5.0"
serde = "1.0.84"
serde_derive = "1.0.84"
osmpbfreader = "0.11"

[workspace]
