[package]
name = "navitia-poi-model"
version = "0.1.0"
authors = ["David Quintanel <david.quintanel@gmail.com>", "Nicolas Bérard <nicolas.berard@kisio.org>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.82"
serde = "1.0.82"
geo = "0.6"
