[package]
name = "navitia-poi-model"
version = "0.1.0"
authors = ["David Quintanel <david.quintanel@gmail.com>", "Nicolas Bérard <nicolas.berard@kisio.org>"]
license = "AGPL-3.0"
description = "Navitia's POIs (Point of Interest) model"
repository="https://github.com/CanalTP/tartare-tools"
edition = "2018"

[dependencies]
serde_derive = "1.0.91"
serde = "1.0.91"
geo = "0.12.1"
